### ISSUE TITLE
threepl: Unexpect packet type: 0x209 [sic!]

### ISSUE THREAD

**Issue by davidfoerster** [hbruintjes/ceema#7]
Starting today I receive the error message in the title when I try to connect to my Threema account via Pidgin (v2.14.10). Pidgin then disables the account. Is that some protocol change that threepl/ceema don’t support (yet)? Note that I had to change the server configuration as per #5.

Is there some further info or logs that you need to debug the issue?

**Comment by hbruintjes** [comment]
That is most likely some new feature in the protocol that is not supported. I've stopped development on this since I do not use it myself, but you can try modifying the code to ignore the error, e.g. wrap the following in an exception handler that does nothing on error:
https://github.com/hbruintjes/ceema/blob/f7b09684d4b6b442cbb1c97f136f8eaab05d3701/src/protocol/session.cpp#L352

**Comment by davidfoerster** [comment]
I did pretty much that and am about to send a pull request.

**Comment by hbruintjes** [comment]
Fixed by #9
